#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Apr 11 22:20:08 2026

@author: lrobledo
"""

# Librerías externas NumPy, SciPy y Matplotlib
from scipy.signal import TransferFunction
import matplotlib.pyplot as plt
import numpy as np


# Librería de TC2, esta la vas a usar mucho
from pytc2.sistemas_lineales import pzmap, GroupDelay, bodePlot

# w0 = 1
# qq = np.sqrt(2)/2

# my_tf = TransferFunction( [w0**2], [1, w0/qq, w0**2] )

q = 10
r1 = 1/2

num = [1, -q*r1]   # s - q*r1
den = [1, q]       # s + q

my_tf = TransferFunction(num, den)

plt.close('all')

bodePlot(my_tf, fig_id=1, filter_description = 'pasa todo' )

pzmap(my_tf, fig_id=2, filter_description = 'pasa todo' )#S plane pole/zero plot

GroupDelay(my_tf, fig_id=3, filter_description ='pasa todo')