#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jul  1 12:18:44 2026

@author: lrobledo
"""

# Librerías externas NumPy, SciPy y Matplotlib
from scipy.signal import TransferFunction
import matplotlib.pyplot as plt
import numpy as np 
from pytc2.sistemas_lineales import pzmap, GroupDelay, bodePlot

from scipy.signal import group_delay

from pytc2.sistemas_lineales import analyze_sys, pretty_print_bicuad_omegayq, tf2sos_analog, pretty_print_SOS

from pytc2.general import print_subtitle
import scipy.signal as sig


# this_order = 5
# this_ripple = 0.4


# z,p,k = sig.buttap(this_order)

# eps = np.sqrt( 10**(this_ripple/10) - 1 )
# num, den = sig.zpk2tf(z,p,k)
# num, den = sig.lp2lp(num, den, eps**(-1/this_order))
psy=0.5088
Q=2.75
num=([1/(2*psy*Q**2),0,0])

den=([1, 1.84/Q, (2+2.19/Q**2), 1.84/Q, 1])

this_sos = tf2sos_analog(num, den)

pretty_print_SOS(this_sos, mode='omegayq')

my_tf = TransferFunction(num, den)

bodePlot(my_tf, fig_id=1, filter_description = 'Cn=5')

pzmap(my_tf, fig_id=2, filter_description = 'Cn=5')

GroupDelay(my_tf, fig_id=3, filter_description = 'Cn=5')



# psy2=0.2589
# den = np.array([1, 0, 1, 0, (1+1/4)/psy2])
# np.roots(den)
# cheby_roots = np.roots(den)
# cheby_roots = cheby_roots[ np.real(cheby_roots) < 0 ]
# cheby_roots
# print("raices", cheby_roots)